### ISSUE TITLE
Write a doc

### ISSUE THREAD

**Issue by prololo** [prologin/stechec2#1]
> ###### Originally posted 2012-05-09 19:25 by [prologin](https://bitbucket.org/prologin/) on Bitbucket

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-13 12:01 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Although the code definitely needs more documentation, this old issue is too broad to be really resolved. There are already some docs for installation and writing rules.
Please create more specific issues if you see some particular things that need to be documented.
