### ISSUE TITLE
Worker node does not handle additional client launch options properly

### ISSUE THREAD

**Issue by delroth** [prologin/stechec2#10]
> ###### Originally posted 2012-05-10 12:33 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

For the 2012 finals a hack was in place for maps but it's crappy and is not handling the general case of additional options. This needs to be done.

**Comment by seirl** [comment]
> ###### Originally posted 2014-05-06 20:01 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Moved in sadm, already fixed.
