### ISSUE TITLE
generator: ocaml: make better use of CAMLparamN and CAMLxparamN

### ISSUE THREAD

**Issue by Dettorer** [prologin/stechec2#100]
About this part of `interface.cc`: https://github.com/prologin/stechec2/blob/70b2f5b9c8fdb7ec225a3b3c18bc8e77b6125814/tools/generator/templates/player/caml/interface.cc.jinja2#L187-L206

- [ ] this code only supports game functions of 5 parameters maximum, and calls a non-existant OCaml macro if used on a game function with more. We should use subsequent calls to `CAMLxparamN` if there is more parameters (grouping theme 5 by 5);
- [ ] this code uses the [`caml_cxx_args`](https://github.com/prologin/stechec2/blob/70b2f5b9c8fdb7ec225a3b3c18bc8e77b6125814/tools/generator/filters/caml.py#L20) filter to add a dummy `unit` parameter to the parameter list if it's originally empty, then calls the `CAMLparam1` macro with this dummy parameter. This should be unnecessary and we should be able to call `CAMLparam0` instead without any dummy parameter. Handling this the right way should also allow us to delete de jinja filter.

**Comment by seirl** [comment]
Fixed by #101
