### ISSUE TITLE
generator: handle user functions with args and a return value

### ISSUE THREAD

**Issue by remi-dupre** [prologin/stechec2#105]
Currently, C interface doesn't implement any type conversion for the arguments and return values of user functions.

More generally, it appears that we need to specify some way of avoiding conflicts in the linking when the same function name is defined through several layers of wrapper.

https://github.com/prologin/stechec2/pull/103 defines some examples of breaking tests.

**Comment by Shaac** [comment]
Maybe to really not be considered as a bug we should add a check in the parsing of the yaml for now.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/105
