### ISSUE TITLE
C# generator: fix broken struct/array handling

### ISSUE THREAD

**Issue by seirl** [prologin/stechec2#117]
This test currently does not work for C#, which indicates array handling is broken inside structures: https://github.com/prologin/stechec2/blob/e944b8b1a9d68fdd71c9be312ca70f12a10388c9/tools/generator/test/languages/champion.cs#L92-L109

How to reproduce and debug:

1. Uncomment the XFAIL test at the end of `tools/generator/test/languages/champion.cs`
2. From the `tools` directory run:

  ```bash
  PYTHONPATH=. pytest --pdb -s -v generator/test/test_languages.py::TestLanguages::test_csharp
  ```

  This will drop you in a PDB shell when the test fails.

3. Use PDB to get the temporary directory where the fail happens:

```
(Pdb) up
(Pdb) p language_dir
PosixPath('/tmp/stechec2-generator-test-xa5r7u7h/cs')
```

4. You can now debug in this directory why the assertions fail.

**Comment by Melyodas** [comment]
https://github.com/prologin/stechec2/blob/master/tools/generator/templates/player/cs/interface.cc.jinja2#L178
Here, mono_field_set_value takes a pointer to a MonoObject, because cxx2lang_array already returns an array, we should not dereference it.
