### ISSUE TITLE
Match dump circuitry

### ISSUE THREAD

**Issue by pmderodat** [prologin/stechec2#13]
> ###### Originally posted 2013-03-29 20:40 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Each year, mechanisms are re-implemented for dumping the game state at each turn for matches. As far as I know, this is done by:

- implementing a “dump_game_state”-like function that returns a C string containing a JSON representation of the game state
- creating a spectator that puts one JSON game state per turn in one line each in a text file
- configure everything so the spectator produce the match dump as expected.

The “dump_game_state” part is very rules-specific: one could implement generic serializers for data structures like arrays, matrices and records, like using the Buffer protocol. But generally:

- the JSON dump do not map physical rules data structures: JSON cells in maps can directly contain units, whereas units may be located in a dedicated data structure in C++ rules, for instance
- the Buffer protocol is handy when both ends use the same code for buffer handlers (most of the time, a client serialize an action with the Action::handle_buffer method, and the server unpack it with the same method), but this is no longer relevant for match dumps: they are generated by rules code, but they are decoded mostly by the Python graphical viewer, so decoding code has to be written twice in two different languages.
- dumping a game state in JSON is quite easy and implementing can be done quickly: no more than 4 hours, testing included :-)

*So*, it would be nice to include an option or a configuration entry somewhere in the stechec server, for example, to dump a match easily without having to write/configure a dedicated spectator for that. Rules should only have to provide the “dump_game_state” function, the rest would be the same every year and thus could be integrated to stechec2.

Thanks in advance!

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-14 01:43 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

PR to review: https://bitbucket.org/prologin/stechec2/pull-requests/10/match-dump-circuitry-implements-13/diff

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-14 12:34 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Implemented by 830512b1ff81
