### ISSUE TITLE
Implement dry run mode for clients

### ISSUE THREAD

**Issue by audebert** [prologin/stechec2#136]
* Add `--dry-run` flag to clients. In this mode no champion is loaded and the client does not send any action to the server. This would be used for integration testing.

**Comment by audebert** [comment]
Closed in favor of #140

**Comment by audebert** [comment]
Re-opened, dry run mode for clients would solve another problem.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/136
