### ISSUE TITLE
Versioning/timestamp of states for TurnBasedRules

### ISSUE THREAD

**Issue by Shaac** [prologin/stechec2#137]
A TurnBasedRules game is just a succession of states, these states can be dumped and viewed with the GUI. But what state exactly is dumped? What exactly is showed by the GUI? When the spectator hits “next turn”, what is the next state the GUI jumps to?

Of course all choices the GUI will probably change from one game to an other. Some time “next turn” will jump to the next round, sometime to the next player, sometimes maybe even something else. We don’t want to make assumptions about that, probably not even how often the game state is dumped.

What we can and should do however, is be able to say with precision what is a given state, and call it by a name. Be able to compare to states, see which comes before the other, and be able to say things like “this is the state in the round 3, where player 2 has just finished her first action”. That way, the GUI will be able to jump from one state to an other with ease, and resume playing afterwards. The dump can keep dumping whenever it wants, but then it will know exactly what it is dumping.

The event of a TurnBasedRules game, and their order, are defined by the implementation of `TurnBasedRules::server_loop`. This order is the same for every single game that is a TurnBasedRules. So we can think clearly about a versioning/timestamp system for the states that we can use for every of these games.

Here is my proposal (it is what we agreed about last year if I remember correctly):

```
for R = 0 to last_round - 1
    R.0.0
    start_of_round
    R.1.0

    for P = 1 to number_players
        R.P.0
        start_of_(player_)turn
        R.P.1(.0)

        for A = 0 to number_actions - 1
            R.P.1.(A-1)
            apply_action
            R.P.1.A
        endfor(A)

        R.P.2
        end_of_(player_)turn
        R.(P+1).0
    endfor(P)

    R.(number_players+1).0
    end_of_round
    (R+1).0.0
endfor(R)
```

This versioning would be the same for every TurnBasedRule, to simplify making reusable GUI parts. For the example above (“this is the state in the round 3, where player 2 has just finished her first action”), the version would be 2.2.1.1.

Then the different games should add even more precision to this, because one action can be subdivided in several steps. So we could have for instance, if in a game a unit is making a move, which is shown on the GUI as moving left then down, and this action scores point:

```
2.2.1.0.0
the unit starts to move left
2.2.1.0.1
the unit then moves down
2.2.1.0.2
this action increases the points of the player
2.2.1.1
```

That way every single state change is just a transition from a versioned state to an other. The GUI knows what it manipulates, and it speaks the same language as the dump system.

How and when the dumps are generated is an other issue. Let’s at least agree on this numbering system, and keep a log of it this time.

Ping @audebert @seirl @fnareoh @Zopieux as we’ve talked about this before.

**Comment by Shaac** [comment]
As a follow-up, about the current state:

The dumper currently dumps at the end of each player turn, which is not enough because the dump of each of the first player’s turn will contain the diff of her turn, like for the other players, but also the end of round. We’re missing the dump of R.1.0 here (except for 0.1.0 which is here, adding even more confusion).

The spectator, is called whenever there is a dump, so they are rather synchronized. Except for that 0.1.0 state where the spectator is not called, but there is a dump, adding numerous bug in factorize spectator and replay GUIs.

**Comment by fnareoh** [comment]
To summarize IRC-discussion of this afternoon: There is an agreement on the importance of those timestamps and that at the same time the control of when to dump should be given to the game's rules, but one question remains where to implement this notion of versioning/timestamp?

The goal is to have something consistent across all future game and two solutions are considered:
1. Adding it to server loop in stechec rules.cc: this way we are sure that the next game will have it, not much maintenance needed, and as it is a general notion that doesn't depend on the game it could be outputted in logs and is overall relevant to this part of the code.
2. Implementing by default this notion in each game's rule through new "dump_json.cc/.hh" files generated from the start that overwrite each method as `start_of_round`, `start_of_(player_)turn`, etc. As the structure is mostly defined with respect to those functions implemented by the game (but not dependant on the game), it could be coherent. This way the timestamps would be very apparent in the game's rules and all dump implementation would be in the game rules making gui implementation and global understanding easier for new server teams not familiar with stechec. But this solution is heavier and harder to maintain.

I personally have a preference for 2, and @Shaac for 1,  @audebert @seirl @Zopieux what do you think ?

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/137
