### ISSUE TITLE
rules generator assumes that actions error type is called `error`

### ISSUE THREAD

**Issue by pguenezan** [prologin/stechec2#143]
Redefine `afficher_erreur` in `interface.cc` and in `api.{cc,hh}`, `erreur` is rename to `error`

**Comment by remi-dupre** [comment]
More generally, I think we want to map errors to a user-defined type.

[This is not the first time that it seems that errors could use a special treatment](https://github.com/prologin/stechec2/issues/89), so maybe it would be a good idea to implement such a thing.

A simple way to handle it would be to add a boolean field `is_error_type` to enum definitions, however it doesn't explicit the fact that there must be one and exactly one of such type.

**Comment by seirl** [comment]
> however it doesn't explicit the fact that there must be one and exactly one of such type.

Is that something we want to enforce? I don't see why we couldn't have multiple error types for different functions.

**Comment by remi-dupre** [comment]
> Is that something we want to enforce? I don't see why we couldn't have multiple error types for different functions.

I'm thinking about the error type attached to the API, which will be returned by actions. This "special" error type is passed as a template parameter to `rules::Api` [here](https://github.com/prologin/stechec2/blob/master/src/lib/rules/api.hh#L14).

**Comment by seirl** [comment]
Yes, I know that it got recently specialized to always work that way, I'm just not sure that's a good approach. Conceptually there is really no reason why all API functions should return the same error type.

**Comment by remi-dupre** [comment]
The logic around errors seems very short and quite easy to generalize indeed.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/143
