### ISSUE TITLE
rules generator generates french display functions

### ISSUE THREAD

**Issue by remi-dupre** [prologin/stechec2#144]
Display functions are generated in [interface.cc](https://github.com/prologin/stechec2/blob/master/tools/generator/templates/rules/src/interface.cc.jinja2#L51)

Even though it is a very forgettable issue, I think that we are that close to get a fully international generator.

Note that if we don't care about generating a bit of french code, we can also solve https://github.com/prologin/stechec2/issues/143 by just assuming that the error type will be called `erreur`.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/144
