### ISSUE TITLE
rules generator generates two definition for type display functions

### ISSUE THREAD

**Issue by remi-dupre** [prologin/stechec2#145]
Functions `afficher_TYPENAME` come with a generated implementation, but they are also part of `game.function`, thus we get a second definition [in interface.cc](https://github.com/prologin/stechec2/blob/master/tools/generator/templates/rules/src/interface.cc.jinja2#L28-L35).

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/145
