### ISSUE TITLE
Generator: constants are not tested in most languages

### ISSUE THREAD

**Issue by seirl** [prologin/stechec2#174]
Right now they are only tested in c, c++ and rust:

```
% git grep CONST_ tools/generator/test/languages/*           
tools/generator/test/languages/champion.c:    assert(CONST_VAL/4 == 10);
tools/generator/test/languages/champion.c:    assert(CONST_DOUBLE == 42.42);
tools/generator/test/languages/champion.cc:    assert(CONST_VAL / 4 == 10);
tools/generator/test/languages/champion.cc:    assert(CONST_DOUBLE == 42.42);
tools/generator/test/languages/champion.rs:    assert!(CONST_VAL / 4 == 10);
tools/generator/test/languages/champion.rs:    assert!(CONST_DOUBLE == 42.42);
```

In #170 the new string constant was tested by replacing its value ("TTY") in other tests. We should probably make these separate tests. The struct test should always be tested with a literal value ("TTY"), and another test should check the value of the constant (assert CONST_STRING == "TTY") in all languages.

@LeSeulArtichaut would you want to take this as a follow up to #170 ?

**Comment by LeSeulArtichaut** [comment]
Looking now
