### ISSUE TITLE
Clean the current code

### ISSUE THREAD

**Issue by prololo** [prologin/stechec2#2]
> ###### Originally posted 2012-05-09 19:27 by [prologin](https://bitbucket.org/prologin/) on Bitbucket

There are lots of ugly things currently in the codebase due to the fact that Stechec 2 was written in a rush.

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-13 12:02 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Although the code definitely needs to be cleaned, this old issue is too broad to be really resolved. A lot of code changed since the 2012 finals. 
Please create more specific issues if you see some particular things that need to be cleaned.
