### ISSUE TITLE
Struct arguments for API functions don't work in some cases (name collisions)

### ISSUE THREAD

**Issue by nguyentito** [prologin/stechec2#20]
> ###### Originally posted 2015-04-22 05:24 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

That case being when a function has both an argument of type X and an argument named X (possibly, but not necessarily, the same argument).

This seems to be related to template expansion rules.

Suggested fix: detect and reject this case in the generator script.

Steps to reproduce the bug:

* run `generator player` on the attached YAML file
* enter the `c/` directory
* run `make`
* get the error given in the attachment

Note: for some reason, running `make` in `cxx/` doesn't fail on the `foobarology_fail1` function, whereas it does in `c/`.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-22 23:48 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

**Comment by seirl** [comment]
> ###### Originally posted 2016-04-11 16:33 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

18:31 <zopieux> je regarde #20

**Comment by zopieux** [comment]
> ###### Originally posted 2016-04-11 17:40 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

generator: forbid same-name arguments; forbid same-name type & argument; fix #20


→ <<cset ce663bc4ec81>>
