### ISSUE TITLE
Export statistics about matches execution

### ISSUE THREAD

**Issue by Dettorer** [prologin/stechec2#21]
> ###### Originally posted 2015-04-27 13:41 by [Dettorer](https://bitbucket.org/Dettorer/) on Bitbucket

* Number of timeout per player
* Time of execution per turn
* Number of action per turn

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-27 14:14 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

- Player language
- OOM
- Opposing player
- Map name

**Comment by seirl** [comment]
> ###### Originally posted 2016-03-30 23:55 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

* Number of timeout per player: useless, kicked after the first one
* OOM: maybe check the isolate meta data file?
* Number of action per turn, opposing player, map name, player language -> those can all be infered from outside stechec2 (dumps and websites)

What statistics do we *really* need to be exported by stechec2?

**Comment by seirl** [comment]
> ###### Originally posted 2016-04-16 22:47 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

I think most of the ideas here are not stechec2-specific and should be implemented in the rules (probably `dump_gamestate()`)
