### ISSUE TITLE
Add support for linking with OCaml libraries

### ISSUE THREAD

**Issue by nguyentito** [prologin/stechec2#22]
> ###### Originally posted 2015-04-29 02:08 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

The main use case would be Batteries, but one should think as well of the libraries included in the standard OCaml distribution which are not, properly speaking, the "standard library" (see the list in Part IV of http://caml.inria.fr/pub/docs/manual-ocaml/ ) and which need to be linked explicitly (e.g. str.cma, num.cma, etc.).

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-13 12:09 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Coud you please provide more details about your findings on the need to recompile the OCaml binaries to achieve that?

**Comment by nguyentito** [comment]
> ###### Originally posted 2016-04-03 18:42 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Hum, as I remember it 1 year later: the OCaml distribution in Arch Linux is not compiled as position-independent code, so when stechec2 tries to bundle the .cma files (which are actually compiled from C code) of the aforementioned libraries into a .so, it fails.

**Comment by seirl** [comment]
> ###### Originally posted 2016-04-22 21:37 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

This requires too much work (using a custom version of ocaml compiled with -fPIC, compiling with ocamlopt, etc). I'll be glad to review a PR if the demand is high enough and it doesn't require too much work to install.

For the record: http://pastie.org/private/txjy005etisaacna7svhmq
