### ISSUE TITLE
stechec2-server and stechec2-client don't warn you your command line is wrong until all clients have connected

### ISSUE THREAD

**Issue by nguyentito** [prologin/stechec2#24]
> ###### Originally posted 2015-05-04 15:24 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

This makes manually launching a match (in order to use gdb/valgrind/whatever, for example) a pain in the ass.

**Comment by seirl** [comment]
> ###### Originally posted 2015-05-04 15:37 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Some checks are part of the rules, and we are not going to call the client loops when the game is not started yet. Wontfix.
