### ISSUE TITLE
Add instructions for makepkg

### ISSUE THREAD

**Issue by emersion** [prologin/stechec2#25]
> ###### Originally posted 2015-05-23 19:02 by [emersion](https://bitbucket.org/emersion/) on Bitbucket

Another install method is:
```
#!bash
cd pkg/stechec2
makepkg
pacman -U stechec2-XXX.pkg.tar.xz
```

This should be documented in README.

**Comment by seirl** [comment]
> ###### Originally posted 2015-10-13 01:16 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Added in 6546f6e4bf10
