### ISSUE TITLE
spectators are not  working

### ISSUE THREAD

**Issue by prololo** [prologin/stechec2#30]
> ###### Originally posted 2016-02-17 10:14 by [choclate](https://bitbucket.org/choclate/) on Bitbucket

I tried to spectate a prologin2013 and a prologin2015 game, but it does not seem to work.

I got a result when using stechec2-run config.yml without spectators.

With the dumper, I have no dump.json
With the gui, I got a black screen and nothing is happening.

Here is my config file:
```
rules: /usr/lib/libprologin2015.so
map: ../maps/map_52.txt
verbose: 1
clients:
    - ./caml_dummy_ai/champion.so
    - ./hs/champion.so
spectators:
    - ../spectators/dumper/dumper.so
```

**Comment by seirl** [comment]
> ###### Originally posted 2016-03-30 23:10 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

I can't reproduce it locally, both clients work. Are you sure both spectators are compiled? Can you debug them by passing -d 3 to stechec2-run?

**Comment by seirl** [comment]
> ###### Originally posted 2016-04-11 16:28 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Cannot reproduce, please reopen if it still happens with a debug trace (or come in #prologin @ irc.freenode.net to get help!)
