### ISSUE TITLE
Get rid of the pub/sub socket

### ISSUE THREAD

**Issue by Dettorer** [prologin/stechec2#34]
The pub/sub socket type from ZMQ makes the assumption that it's ok for subscribers to miss a few updates from the publisher and does not make sure they receive everything, it's a tradeoff for scalability.

This is why clients sometimes hang in the middle of a game (and more frequently at the beginning), they are actually missing an update on the pub/sub socket, for example because they started to listen on the socket just after the server sent its update.

I suggest replacing the pub/sub socket with one req/rep per client and changing the following commandline options:

client:
- keep `--req_addr addr`
- change `--sub_addr addr` to `--rep_addr addr`

server:
- keep `--rep_addr addr`
- change `--pub_addr addr` to `--req_addrs client1,client2,...`

**Comment by seirl** [comment]
@kalenz

**Comment by zopieux** [comment]
What about not using ZMQ altogether?

**Comment by Dettorer** [comment]
That's probably better, but I won't have the time to do that for this weekend, what I suggest is a temporary solution.

**Comment by Dettorer** [comment]
Another temporary solution would be to keep the pubsub socket and, in the clients, to have a thread continuously listening on the sub socket, adding the received data in a buffer queue. The regular ClientSocket::pull() would then simply pop from that queue (and wait if it's empty).

Would launching a thread be problematic?

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/34
