### ISSUE TITLE
Fix PHP generator

### ISSUE THREAD

**Issue by prololo** [prologin/stechec2#4]
> ###### Originally posted 2012-05-09 19:29 by [prologin](https://bitbucket.org/prologin/) on Bitbucket

Apparently PHP does not work. To investigate.

**Comment by seirl** [comment]
> ###### Originally posted 2013-04-11 17:09 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

8ed0c9c fixed a small issue, everything seems to work otherwise.

**Comment by seirl** [comment]
> ###### Originally posted 2013-04-15 21:25 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Apparently the PHP API segfaults when retrieving a struct, this needs to be fixed.

**Comment by seirl** [comment]
> ###### Originally posted 2013-04-21 03:43 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Solved by a6538dd
