### ISSUE TITLE
Allow the rules to export stats of the games

### ISSUE THREAD

**Issue by seirl** [prologin/stechec2#42]
It would be cool if the rules had a way to export in their result some infos like:

- Number of turns
- Number of {action} done by each participant
- ...

This would allow us to show cool stats to the contestants, like:

- Shortest match
- Match with the greatest number of {action}
- ...

**Comment by audebert** [comment]
Let's store the stats in files in the format described in: https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-format-details

Those files can then be consumed by https://github.com/prometheus/node_exporter#textfile-collector or by a simple parser to be displayed in the web interface.

Note: storing the match id and player id in metric labels will cause an explosion in metrics cardinality, we'll need to figure out how to aggregate those, which may be as simple as using https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules

**Comment by audebert** [comment]
Stats can also be emitted in logs, which can be processed by ElasticSearch and queried in Kibana.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/42
