### ISSUE TITLE
Add Haskell generator

### ISSUE THREAD

**Issue by prololo** [prologin/stechec2#6]
> ###### Originally posted 2012-05-09 19:32 by [prologin](https://bitbucket.org/prologin/) on Bitbucket

There is demand for Haskell support. Is it worth it?

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-29 12:33 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Solved by pull requests 2 and 3; thanks Rafbill!
