### ISSUE TITLE
Simplify use at home

### ISSUE THREAD

**Issue by Shaac** [prologin/stechec2#64]
Stechec works fine in the context of Prologin’s final. But what of the people who want to code a champion at home? If someday we manage to finally host a contest website with old final games, people who want to participate will still need to install stechec, bundled with the specific game. The installation is not so easy on linux, probably not possible on windows…

And even once everything is installed, there are many generated files. For instance, a python developer would only code in a single python file, but still have the interface.cc file, a complicated makefile. Maybe all of this is not necessary

There should be some way to provide some kind of SDK, so that someone who want to code a champion, has little thing to do to start coding, and then generate a .so to upload to the website.
There is no need for the user to even download the complete rules. Just to have the interface.hh, and the wrapper for any chosen language. Something simple to be able to develop a champion at home without any kind of complicated installation.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/64
