### ISSUE TITLE
Namespace the generated rules

### ISSUE THREAD

**Issue by Shaac** [prologin/stechec2#65]
We should generate the rules under any kind of namespace (cannot be `rules`, because there is already a `rules::Api` and we generate a `Api` class). Could be `prolo`, or even the name in the input yaml.

I’ve seen several time someone code a C++ champion, and struggling to understand why his program does not link/behaves strangely, because the champion also contains a `Gamestate` class.

**Comment by audebert** [comment]
+1 for the game name (prologin2020::, tictactoe::, etc.)

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/stechec2/-/issues/65
