### ISSUE TITLE
Master node should check the worker hostname

### ISSUE THREAD

**Issue by delroth** [prologin/stechec2#8]
> ###### Originally posted 2012-05-10 11:38 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Currently the master node accepts workers even when their hostname are not resolving propetly, causing problems when it has to send them tasks later. These workers should be refused directly when they announce themselves to the master node.

Alternatively, use something else than the hostname to handle this (remote IP).

**Comment by seirl** [comment]
> ###### Originally posted 2014-05-06 20:02 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Moved to sadm
