### ISSUE TITLE
Handle different shared data mountpoints for workers and website

### ISSUE THREAD

**Issue by delroth** [prologin/stechec2#9]
> ###### Originally posted 2012-05-10 12:25 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Currently the master/worker system only works when using the same path for the shared stechec data (NFS). When the website uses /exports/homes and the workers use /home it does not work.

**Comment by seirl** [comment]
> ###### Originally posted 2014-05-06 20:02 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Moved in sadm, solved.
